# Profile information
name: Aussie Trip
title: Aussie Trip - Blog sobre les meves aventures a Australia
description: > # this means to ignore newlines until "baseurl:"
  Moltes històries, imatges i anècdotes que havien de ser plasmades en un sol lloc.
  Un lloc que permetrà recordar tot el succeït durant aquests vuit mesos a aquest país.
  Un país enorme i inexplorat ple d'aventures a explicar en aquest blog.
  Passin i vegin.
permalink: ':title/'
baseurl: "/aussie-trip" # the subpath of your site, e.g. /blog
url: "albertsuarez.me" # the base hostname & protocol for your site, e.g. http://example.com

# Social
facebook: suaarezz
twitter: alsumo95
instagram: albert.suarezz
github: AlbertSuarez

# Analytics
analytics: UA-110581543-1

# Comments
discus-identifier: albertsuarez-me

# Paginate
paginate: 5
paginate_path: /page:num/

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
include: [_pages]
