# Profile information
name: Aussie Trip
title: Aussie Trip - Blog sobre les meves aventures a Australia
description: > # this means to ignore newlines until "baseurl:"
  Moltes històries, imatges i anecdotes que havien de ser plasmades en un sol lloc.
  Aquest lloc permetrà recordar tot el succedit durant aquests vuit mesos a les antípodes.
permalink: ':title/'
baseurl: "/aussie-trip" # the subpath of your site, e.g. /blog
url: "albertsuarez.me" # the base hostname & protocol for your site, e.g. http://example.com

# Social
facebook: suaarezz
twitter: alsumo95
google-plus: +AlbertSuárezMolgó
github: AlbertSuarez

# Contact form
email: alsumo95@gmail.com

# Comments
discus-identifier: # Add your Disqus identifier

# Paginate
paginate: 5
paginate_path: /page:num/

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
include: [_pages]
